filebeat.inputs:
  - type: filestream
    id: nginx-access
    paths:
      - nginx_logs:/var/log/nginx

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

setup.kibana:
  host: "http://kibana:5601"

setup.template.enabled: true
setup.template.overwrite: true
setup.ilm.enabled: false   

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
